### ISSUE TITLE
Launch simple mapper

### ISSUE THREAD

**Issue by FranciscoJManasAlvarez** [knmcguire/crazyflie_ros2_experimental#1]
Hi,

I am currently working in my lab with crazyflies in ROS2 and the simulation until now was done with Gazebo in ROS Noetic. When I saw this work I was enjoy to see the simulation in ROS2 (even if it was in webots). I have tried to launch simple mapper but it was missing the cffirmware. I have cloned myself crazyswarm2 (I get some error when compiling) but I have made the configuration of the software simulation in the loop.

I changed https://github.com/knmcguire/crazyflie_ros2_experimental/blob/1a880465997a0c765e57525da6dc97b1c0d672dc/crazyflie_ros2_simulation/crazyflie_ros2_simulation/crazyflie_webots_driver.py#L15 to cfsim folder of crazyswarm2 repo and when i launch simple mapper this is the result:
```
[INFO] [launch]: All log files can be found below /home/kiko/.ros/log/2022-07-07-18-21-08-874676-kiko-HP-ZBook-103229
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [webots-1]: process started with pid [103232]
[INFO] [driver-2]: process started with pid [103234]
[INFO] [robot_state_publisher-3]: process started with pid [103237]
[driver-2] Cannot open file: /tmp/webots-103232-lxyt4b/WEBOTS_SERVER (retry count 1)
[robot_state_publisher-3] Parsing robot urdf xml string.
[robot_state_publisher-3] [INFO] [1657210868.967780395] [robot_state_publisher]: got segment 
[driver-2] Cannot open file: /tmp/webots-103232-lxyt4b/WEBOTS_SERVER (retry count 2)
[driver-2] Cannot open file: /tmp/webots-103232-lxyt4b/WEBOTS_SERVER (retry count 3)
[robot_state_publisher-3] Parsing robot urdf xml string.
[robot_state_publisher-3] Link body had 0 children
[robot_state_publisher-3] Link camera had 0 children
[robot_state_publisher-3] Link gps had 0 children
[robot_state_publisher-3] Link gyro had 0 children
[robot_state_publisher-3] Link inertial unit had 0 children
[robot_state_publisher-3] Link range_back had 0 children
[robot_state_publisher-3] Link range_front had 0 children
[robot_state_publisher-3] Link range_left had 0 children
[robot_state_publisher-3] Link range_right had 0 children
[robot_state_publisher-3] Link solid_0 had 0 children
[robot_state_publisher-3] Link solid_1 had 0 children
[robot_state_publisher-3] Link solid_2 had 0 children
[robot_state_publisher-3] Link solid had 0 children
[robot_state_publisher-3] [INFO] [1657210872.379969651] [robot_state_publisher]: got segment base_link
[robot_state_publisher-3] [INFO] [1657210872.379988398] [robot_state_publisher]: got segment body
[robot_state_publisher-3] [INFO] [1657210872.379991251] [robot_state_publisher]: got segment camera
[robot_state_publisher-3] [INFO] [1657210872.379993656] [robot_state_publisher]: got segment gps
[robot_state_publisher-3] [INFO] [1657210872.379996054] [robot_state_publisher]: got segment gyro
[robot_state_publisher-3] [INFO] [1657210872.379999465] [robot_state_publisher]: got segment inertial unit
[robot_state_publisher-3] [INFO] [1657210872.380002079] [robot_state_publisher]: got segment range_back
[robot_state_publisher-3] [INFO] [1657210872.380004431] [robot_state_publisher]: got segment range_front
[robot_state_publisher-3] [INFO] [1657210872.380006740] [robot_state_publisher]: got segment range_left
[robot_state_publisher-3] [INFO] [1657210872.380009063] [robot_state_publisher]: got segment range_right
[robot_state_publisher-3] [INFO] [1657210872.380011337] [robot_state_publisher]: got segment solid
[robot_state_publisher-3] [INFO] [1657210872.380013574] [robot_state_publisher]: got segment solid_0
[robot_state_publisher-3] [INFO] [1657210872.380015837] [robot_state_publisher]: got segment solid_1
[robot_state_publisher-3] [INFO] [1657210872.380018087] [robot_state_publisher]: got segment solid_2
[driver-2] Traceback (most recent call last):
[driver-2]   File "/home/kiko/roboticpark_ws/build/crazyflie_ros2_simulation/crazyflie_ros2_simulation/crazyflie_webots_driver.py", line 62, in init
[driver-2]     cffirmware.controllerPidInit()
[driver-2] AttributeError: module 'cffirmware' has no attribute 'controllerPidInit'
[driver-2] Traceback (most recent call last):
[driver-2]   File "/home/kiko/roboticpark_ws/build/crazyflie_ros2_simulation/crazyflie_ros2_simulation/crazyflie_webots_driver.py", line 76, in step
[driver-2]     rclpy.spin_once(self.node, timeout_sec=0)
[driver-2] AttributeError: 'CrazyflieWebotsDriver' object has no attribute 'node'
```

I understand the second error (The first failure causes the node not to be created), but i don't know how fix the first. Can you told me the repos that i need or if i missing some configuration steps? 

Thanks

**Comment by knmcguire** [comment]
Hi! Sorry I completely missed this. I'm happy that you are trying this out as well but I must apologize that this is still a very experimental repository and very hackish, so a lot of bugs are expected and the readme is not completely readable I'm afraid. Once this project is done, it will be converted to the bitcraze organization to a more suitable form.

Anyway, it seems that your issue is because you are not pointing to the [crazyflie-firmware ](https://github.com/bitcraze/crazyflie-firmware) repo with a `make bindings_python`

Btw, the experimental crazyflie simulation repo can be found here: https://github.com/bitcraze/crazyflie-simulation, that one also has it explained in the readme.

**Comment by knmcguire** [comment]
I've updated the readme to mention this. Hope this works!

**Comment by FranciscoJManasAlvarez** [comment]
I understand it perfectly .

Thank you very much.
